---

- name: "Make fencing quote csv at {{ quote_path }}"
  vars:
    days: |-
      {%- for type in fencing -%}
        {%- if email_facts.fence_type == type.email_string -%}
          {{ email_facts.fence_length / type.feet_per_day }}
        {%- endif -%}
      {%- endfor -%}
    materials: |-
      {%- set material = [] -%}
      {%- for type in fencing -%}
        {%- if (email_facts.fence_type == type.email_string) and
               (email_facts.height is not defined) -%}
          {%- for item in type.material -%}
            {%- set _ = material.append({
              "name": item,
              "qty": (email_facts.fence_length * email_facts.fence_height) / type.length
              }) -%}
          {%- endfor -%}
        {%- endif -%}
        {%- if (email_facts.fence_type == type.email_string) and
               (email_facts.height is defined) and
               (email_facts.height == item.height) -%}
          {%- for item in type.material -%}
            {%- set _ = material.append({
              "name": item,
              "qty": email_facts.fence_length / type.length
              }) -%}
          {%- endfor -%}
        {%- endif -%}
      {%- endfor -%}
      {%- for type in posts -%}
        {%- if (email_facts.fence_post_type == type.email_string) and
               (email_facts.fence_height == type.height) -%}
          {%- for item in type.material -%}
            {%- set _ = material.append({
              "name": item,
              "qty": email_facts.fence_length / 8
              }) -%}
          {%- endfor -%}
          {%- if "Round wood posts" in type.email_string -%}
            {%- set _ = material.append({
              "name": hardware.fence_nails.url,
              "qty": (email_facts.fence_height * (email_facts.fence_length / distance_between_posts)) / hardware.fence_nails.qty
            }) -%}
          {%- endif -%}
          {%- if "T-posts" in type.email_string -%}
            {%- set _ = material.append({
              "name": hardware.t_post_clips.url,
              "qty": (email_facts.fence_height * (email_facts.fence_length / distance_between_posts)) / hardware.t_post_clips.qty
            }) -%}
          {%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {%- for type in gates -%}
        {%- if (email_facts.gate_type == type.email_string) and
               (email_facts.gate_length == type.length) -%}
          {%- for item in type.material -%}
            {%- set _ = material.append({
              "name": item,
              "qty": email_facts.gate_qty
              }) -%}
          {%- endfor -%}
        {%- endif -%}
      {%- endfor -%}
      {%- if email_facts.gate_opener_qty > 0 -%}
        {%- for item in gate_openers.material -%}
          {%- set _ = material.append({
            "name": item,
            "qty": email_facts.gate_opener_qty
          }) -%}
        {%- endfor -%}
      {%- endif -%}
      {%- if email_facts.hotwire_inside == "Yes" -%}
        {%- for item in hotwire.material -%}
          {%- if item.name == "hotwire" -%}
            {%- set _ = material.append({
              "name": item.url,
              "qty": email_facts.fence_length / item.length
             }) -%}
          {%- elif item.name == "insulators" -%}
            {%- set _ = material.append({
              "name": item.url,
              "qty": (email_facts.fence_length / distance_between_posts) / item.qty
            }) -%}
          {%- elif ("ground" in item.name) or
                   ("solar" in item.name) -%}
            {%- set _ = material.append({
              "name": item.url,
              "qty": 1
            }) -%}
          {%- endif -%}  
        {%- endfor -%}
      {%- endif -%}
      {%- if email_facts.paint == "Yes" -%}
        {%- for item in paint.material -%}
          {%- set _ = material.append({
            "name": item.name,
            "qty": email_facts.fence_length / item.feet
          }) -%}
        {%- endfor -%}
      {%- endif -%}
      {{ material }}
    equipment: |-
      {%- set equipment = fencing_equipment.equipment -%}
      {%- if ("Pipe" in email_facts.fence_type) or
             ("pipe" in email_facts.fence_type) or
             ("Pipe" in email_facts.fence_post_type) -%}
        {%- for item in pipe_fence.equipment -%}
          {%- set _ = equipment.append(item) -%}
        {%- endfor -%}
      {%- endif -%}
      {%- if "Yes" in email_facts.fence_line_clear -%} 
        {%- for item in clear_fence_line.equipment -%}
          {%- set _ = equipment.append(item) -%}
        {%- endfor -%}
      {%- endif -%}
      {%- if "Replace" in email_facts.new_or_replacement -%} 
        {%- for item in clear_fence_line.equipment -%}
          {%- set _ = equipment.append(item) -%}
        {%- endfor -%}
      {%- endif -%}
      {{ equipment }}
  template:
    src: "fencing_quote.j2"
    dest: "{{ quote_path }}"

...
