---

circlejh_equipment:
  mowers:
    - type: "Zero turn"
      min_acres: 0
      max_acres: 2
      min_grass_height: 0
      max_grass_height: 6
      cost: 100
      acres_per_hour: 1
      labor_type: operator
    - type: "Tractor with shredder"
      min_acres: 0
      max_acres: 99
      min_grass_height: 0
      max_grass_height: 36
      cost: 330
      acres_per_hour: 5
      labor_type: operator
    - type: "Tractor with bat-wing shredder"
      min_acres: 100
      max_acres: 9999999999999999999999999
      min_grass_height: 0
      max_grass_height: 48
      cost: 500
      acres_per_hour: 8
      labor_type: operator
  truck:
    cost: 100
  trailer:
    equipment:
      cost: 50
    tool:
      cost: 100
...
