---

- hosts: all
  gather_facts: false
  vars:
    name: "Andy Huffman"
    email: "circlejh@outlook.com"
    phone: "8324706635"
    postal_code: 77423
    acres: 700
    height: 12
    trash: no
    dry: yes
    timeline: ASAP

  tasks:
    - name: Figure out equipment
      set_fact:
        equipment:
          mower: |-
            {%- for mower in circlejh_equipment.mowers -%}
              {%- if (mower.min_acres < acres < mower.max_acres) and
                     (mower.min_grass_height < height < mower.max_grass_height) -%}
            {{ mower }}
              {%- endif -%}
            {%- endfor -%}
          truck_and_equipment_trailer: "{{ circlejh_equipment.truck_and_equipment_trailer }}"

    - name: Figure out time line
      set_fact:
        project: |-
          {%- set hours = ( acres / equipment.mower.acres_per_hour ) | round(0,'ceil') | int -%}
          {%- set days = ( hours / working_day_hours ) | round(0,'ceil') | int -%}
          {%- set weeks = ( days / 5 ) | round(0,'ceil') | int -%}
          {%- set project = {
            "hours": hours,
            "days": days,
            "weeks": weeks
            } -%}
          {{ project }} 

    - name: Figure out costs
      set_fact: 
        cost: |-
          {%- if 0 <= project.days <= 4 -%}
            {%- set mower = equipment.mower.day_cost * project.days -%}
            {%- set truck_and_equipment_trailer = equipment.truck_and_equipment_trailer.day_cost * project.days -%}
          {%- elif project.days >= 5 -%}
            {%- set mower = equipment.mower.week_cost * project.weeks -%}
            {%- set truck_and_equipment_trailer = equipment.truck_and_equipment_trailer.week_cost * project.weeks -%}
          {%- endif -%}
          {%- set total = mower + truck_and_equipment_trailer -%}
          {%- set equipment_cost = {
            "mower": mower,
            "truck and equipment trailer": truck_and_equipment_trailer,
            "total": total 
            } -%}
          {%- set equipment_burden = burden * equipment_cost.total -%}
          {%- set equipment_margin = (equipment_cost.total + equipment_burden) * margin -%}
          {%- set total_equipment_cost = equipment_cost.total + equipment_burden + equipment_margin -%}
          {%- set labor_cost = project.hours * labor[equipment.mower.labor_type] -%}
          {%- set labor_burden = burden * labor_cost -%}
          {%- set labor_margin = (labor_cost + labor_burden) * margin -%}
          {%- set total_labor_cost = labor_cost + labor_burden + labor_margin -%}
          {%- set sales_tax_cost = (total_equipment_cost + total_labor_cost) * sales_tax -%}
          {%- set total_cost = total_equipment_cost + total_labor_cost + sales_tax_cost -%}
          {%- set cost = {
            "equipment cost": equipment_cost.total,
            "equipment burden": equipment_burden,
            "equipment margin": equipment_margin,
            "total equipment cost": total_equipment_cost,
            "labor cost": labor_cost,
            "labor burden": labor_burden,
            "labor margin": labor_margin,
            "total_labor_cost": total_labor_cost,
            "sales tax": sales_tax_cost,
            "total": total_cost 
            } -%}
          {{ cost }}

    - name: Create quickbooks estimate
      uri:
        method: POST
        url: "{{ quickbooks_url }}/estimate?minorversion=70"
        headers:
          Content type: application/json
        body_format: json
        body:
         TotalAmt: 31.5 
         BillEmail: 
          Address: "Cool_Cars@intuit.com"
         CustomerMemo: 
          value: "Thank you for your business and have a great day!"
         ShipAddr: 
          City: "Half Moon Bay" 
          Line1: "65 Ocean Dr." 
          PostalCode: "94213" 
          Lat: "37.4300318" 
          Long: "-122.4336537" 
          CountrySubDivisionCode: "CA" 
          Id: "4"
         PrintStatus: "NeedToPrint" 
         EmailStatus: "NotSet" 
         BillAddr: 
          City: "Half Moon Bay" 
          Line1: "65 Ocean Dr." 
          PostalCode: "94213" 
          Lat: "37.4300318" 
          Long: "-122.4336537" 
          CountrySubDivisionCode: "CA" 
          Id: "4"
         Line:
            Description: "Pest Control Services" 
            DetailType: "SalesItemLineDetail" 
            SalesItemLineDetail: 
              TaxCodeRef: 
                value: "NON"
              Qty: 1 
              UnitPrice: 35 
              ItemRef: 
                name: "Pest Control" 
                value: "10"
            LineNum: 1 
            Amount: 35.0 
            Id: "1"
            DetailType: "SubTotalLineDetail" 
            Amount: 35.0 
            SubTotalLineDetail: 
            DetailType: "DiscountLineDetail" 
            Amount: 3.5 
            DiscountLineDetail: 
              DiscountAccountRef: 
                name: "Discounts given" 
                value: "86"
              PercentBased: true 
              DiscountPercent: 10
         CustomerRef: 
          name: "Cool Cars" 
          value: "3"
         TxnTaxDetail: 
          "TotalTax: 0
         ApplyTaxAfterDiscount: false

#    - name: Send quickbooks estimate to customer
#
#    - name: Send internal estimate to Circle JH

...
