---

- hosts: all
  gather_facts: false
  vars:
    name: "Andy Huffman"
    email: "circlejh@outlook.com"
    phone: "8324706635"
    postal_code: 77423
    acres: 2
    height: 12
    trash: no
    dry: yes
    timeline: ASAP

  tasks:
    - name: Figure out equipment
      set_fact:
        equipment:
          mower: |-
            {%- for mower in circlejh_equipment.mowers -%}
              {%- if (mower.min_acres < acres < mower.max_acres) and
                     (mower.min_grass_height < height < mower.max_grass_height) -%}
            {{ mower }}
              {%- endif -%}
            {%- endfor -%}
          truck_and_equipment_trailer: "{{ circlejh_equipment.truck_and_equipment_trailer }}"

    - debug:
        msg: "{{ equipment }}"

    - name: Figure out time line
      set_fact:
        project:
          hours: "{{ acres / equipment.mower.acres_per_hour | round | ceil | int }}"
          days: "{{ projecthours / working_day_hours | round | ceil | int }}"
          weeks: "{{ projectdays / 5 | round | ceil | int }}"

    - debug:
        msg: "{{ project }}"

    - name: Figure out costs
      set_fact: 
        cost:
          equipment_cost: |-
            {%- if 0 <= project.days <= 4 -%}
              {%- set mower = equipment.mower.day_cost * project.days -%}
              {%- set truck_and_equipment_trailer = equipment.truck_and_equipment_trailer.day_cosxt * project.days -%}
            {%- elif project.days >= 5 -%}
              {%- set mower = equipment.mower.week_cost * project.weeks -%}
              {%- set truck_and_equipment_trailer = equipment.truck_and_equipment_trailer.week_cost * project.weeks -%}
            {%- endif -%}
            {%- set total = mower + truck_and_equipment_trailer -%}
            {%- set equipment_cost = {
              "mower": mower,
              "truck and equipment trailer": truck_and_equipment_trailer,
              "total": total 
              } -%}
            {{ equipment_cost }}" 
        equipment_burden: "{{ set equipment_burden = burden * equipment_cost }}"
        equipment_margin: "{{ set equipment_margin = (equipment_cost + equipment_burden) * equipment_margin }}"
        total_equipment_cost: "{{ set total_equipment_cost = equipment_cost + equipment_burden + equipment_margin }}"
        labor_cost: "{{ set labor_cost = project_hours * labor[equipment.mower.labor_type] }}"
        labor_burden: "{{ set labor_burden = burden * labor_cost }}"
        labor_margin: "{{ set labor_margin = (labor_cost + labor_burden) * labor_margin }}"
        total_labor_cost: "{{ set total_labor_cost = labor_cost + labor_burden + labor_margin }}"
        sales_tax_cost: "{{ set sales_tax_cost = (total_equipment_cost + total_labor_cost) * sales_tax }}"
        total_cost: "{{ set total_cost = total_equipment_cost + total_labor_cost + sales_tax_cost }}"

    - debug:
        msg: "{{ cost }}" 

#    - name: Send quickbooks estimate to customer
#
#    - name: Send internal estimate to Circle JH

...
