---

- hosts: all
  gather_facts: false
  vars:
    name: "Andy Huffman"
    email: "circlejh@outlook.com"
    phone: "8324706635"
    postal_code: 77423
    acres: 2
    height: 4
    trash: no
    dry: yes
    timeline: ASAP

  tasks:

    - name: Make quote csv
      vars:
        equipment:
          mower: |-
            {%- for mower in circlejh_equipment.mowers -%}
              {%- if (mower.min_acres < acres < mower.max_acres) and
                     (mower.min_grass_height < height < mower.max_grass_height) -%}
            {{ mower }}
              {%- endif -%}
            {%- endfor -%}
          truck: "{{ circlejh_equipment.truck }}"
          equipment_trailer: "{{ circlejh_equipment.trailer.equipment }}"
        project: |-
          {%- set hours = ( acres / equipment.mower.acres_per_hour ) | round(0,'ceil') | int -%}
          {%- set days = ( hours / working_day_hours ) | round(0,'ceil') | int -%}
          {%- set weeks = ( days / 5 ) | round(0,'ceil') | int -%}
          {%- set project = {
            "hours": hours,
            "days": days,
            "weeks": weeks
            } -%}
          {{ project }} 
      template:
        src: "{{ playbook_dir }}/../templates/mowing_quote.j2"
        dest: "/tmp/{{ name | replace(' ', '_') }}-mowing-quote.csv"

    - name: Email quote to circlejh@outlook.com
      community.general.mail:
        host: "mailslurp.mx"
        port: 2465
        secure: starttls
        username: ""
        password: "" 
        subject: "Automated quote generation for {{ name }}"
        from: "69733564-13ec-4e6e-8cd0-f392ba01b933@mailslurp.net"
        body: "Quote csv is attached"
        to: "circlejh@outlook.com"
        attach: "/tmp/{{ name | replace(' ', '_') }}-mowing-quote.csv"
        
...
