---

- hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      include_vars:
        dir: "{{ working_dir }}/inventory/group_vars/all"

    - name: Validate request
      assert:
        that:
          - ansible_eda.event.meta.headers.Host == webhook_host
          - ansible_eda.event.meta.headers["x-from"] == webhook_x_from
          - ansible_eda.event.meta.source.name == webhook_source
          - ansible_eda.event.payload.from == webhook_payload_from

    - name: "Get email info for {{ emailId }}"
      vars:
        emailId: "{{ ansible_eda.event.payload.emailId }}"
      import_role:
        name: "{{ working_dir }}/roles/email_facts"

    - name: "Make mowing quote for {{ email_facts.name }}"
      when:
        - email_facts.acres is defined
        - email_facts.height is defined
      import_role:
        name: "{{ working_dir }}/roles/mowing_quote"

    - name: "Send {{ quote_path }} to slack"
      import_role:
        name: "{{ working_dir }}/roles/slack_update"
...
